online_payment:
  outputs:
    dev:
      dataset: final_project_df11_group_1
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: brave-sonar-400508-1b40a9925807.json
      location: US
      method: service-account
      priority: interactive
      project: brave-sonar-400508
      threads: 3
      type: bigquery
  target: dev
