online_payment:
  outputs:
    dev:
      dataset: final_project_df11_group_1 #dataset source in BigQuery
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: brave-sonar-400508-1b40a9925807.json #path key service account GCP
      location: US
      method: service-account
      priority: interactive
      project: brave-sonar-400508 #project name in GCP
      threads: 3
      type: bigquery
  target: dev
