final_project:
  outputs:
    dev:
      dataset: final_project
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: eternal-channel-400514
      threads: 3
      type: bigquery
  target: dev
